# Generated by Django 5.2.11 on 2026-02-23 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Padrão', max_length=100)),
                ('rtsp_url', models.URLField(max_length=500)),
                ('tolerancia_match_percentual', models.PositiveSmallIntegerField(default=85, help_text='Percentual mínimo para considerar match de placa (80-90%).', validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(90)])),
                ('intervalo_frames_ms', models.PositiveIntegerField(default=250, help_text='Intervalo de captura entre frames processados.')),
                ('tentativas_por_evento', models.PositiveSmallIntegerField(default=6, help_text='Quantidade de tentativas de OCR antes do veredito final.')),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='EventoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_lida', models.CharField(db_index=True, max_length=20)),
                ('placa_normalizada', models.CharField(db_index=True, max_length=10)),
                ('confianca_ocr', models.FloatField(default=0.0)),
                ('score_match_percentual', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('autorizado', 'Autorizado'), ('desconhecido', 'Desconhecido')], max_length=20)),
                ('nome_servidor', models.CharField(blank=True, max_length=150, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Evento de leitura',
                'verbose_name_plural': 'Eventos de leitura',
                'ordering': ['-criado_em'],
            },
        ),
    ]
