# Generated by Django 5.2.11 on 2026-02-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='rtsp_url',
            field=models.CharField(help_text='Coloque a URL RTSP ou digite 0 para USB local.', max_length=500),
        ),
    ]
